version: 2

project_name: teams-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: teams-cli
    main: .
    binary: teams-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - teams-cli
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - icons/teams-cli-logo.png

checksum:
  name_template: checksums.txt

changelog:
  use: git

release:
  github:
    owner: aeswibon
    name: teams-cli
